technicalexercise/main/routes.py
from flask import Flask, render_template, Blueprint

main = Blueprint('main', __name__, template_folder='templates',
                 static_folder='static', static_url_path='/static/main')

# Routing
@main.route('/')
def base():
    tab_title = 'Home | T-E'

    return render_template('main/home.html', title=tab_title)


@main.route('/about_us')
def about_us():
    tab_title = 'About Us | T-E'
    about_us = [
        {
            'header': 'QCPU SAKAY',
            'sub_header': 'QCPU SAKAY - A Bus Transportation System',
            'content': '''Good Ride Starts Here. QCPU Sakay is your best commuting buddy that let you commute with ease. 
                        Get an all-in-one app that has Real Time Location Tracking with easy mode of payment. 
                        Just Ride, Locate, Tap and, '../static/img/banner-2.jpg' Scan to pay.''',
            'logo': 'https://websakay.web.app/components/images/logo-one.png',
            'background_color': '#31ccec',
            'background_image': 'none',
            'url': 'https://websakay.web.app/'
        },
        {
            'header': 'ServRevo',
            'sub_header': 'ServRevo Corporation - Seats and Room Reservation System',
            'content': '''ServRevo Corp. (ServRevo) is an outsourcing company providing shared services, co-working spaces, HR/Payroll, and staffing solutions.
                        Our bespoke offshore solutions integrate seamlessly with any business requirement ...''',
            'logo': 'http://www.servrevo.com/img/servrevo-logo.png',
            'background_color': '#21ba45',
            'background_image': 'http://www.servrevo.com/img/services/payroll-2.jpg',
            'url': 'http://www.servrevo.com/'
        },
    ]
    return render_template('main/about_us.html', title=tab_title, about_us=about_us)


@main.route('/contacts')
def contacts():
    tab_title = 'Contacts | T-E'
    return render_template('main/contacts.html', title=tab_title)

technicalexercise/main/templates/main/about_us.html
{% extends 'main/header.html' %}

{% block content %}
{% include 'main/nav_bar.html' %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/main/projects.css')}}">

<!-- Banner Grettings -->
<div id="banner-greetings" class="pos-relative">
    <div class="pos-absolute-center white-text">
        <p class="font-weight-bold r-fs-30">Lorem Ipsum</p>
        <p class="r-fs-20">"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci
            velit..."</p>
    </div>
</div>

<div class="container">
    <h3>Lorem ipsum dolor sit amet:</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor lectus et libero tristique pulvinar. Nulla non
        gravida metus, ut dictum augue. Proin vitae massa nec mauris congue tincidunt. Curabitur ultricies consectetur
        nisi sit amet elementum. Suspendisse sed nibh tellus. Fusce sagittis turpis et sapien ultrices, sed dictum risus
        vehicula. Aenean rhoncus ac felis eget aliquet. Maecenas sed tellus odio. In ut purus cursus, ullamcorper nunc
        in, sagittis metus. Vestibulum tellus arcu, pharetra sit amet scelerisque a, dapibus ac turpis. Donec blandit
        efficitur dui nec venenatis. Proin ornare felis ut volutpat sollicitudin. Mauris vel vulputate nunc. Integer
        mollis nunc nec magna auctor ullamcorper. Nullam eget risus felis. </p>

    <p>Sed consectetur, nisl at luctus mollis, orci tellus gravida felis, eget volutpat risus eros eget risus. Sed
        est nisi, sollicitudin sit amet luctus ut, venenatis a nisl. Duis ut leo ac ante volutpat mollis at et
        lectus. Vestibulum posuere metus vel tincidunt finibus. Donec cursus nunc lacus, at iaculis mauris volutpat
        ut. Fusce egestas ornare elit, in tincidunt justo posuere cursus. Proin eu neque diam. Sed ut tortor sem.
        Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci
        luctus et ultrices posuere cubilia Curae; Aliquam erat volutpat. Fusce id enim vel ex hendrerit suscipit
        vitae eu risus. Pellentesque tempus magna et consequat rhoncus. Nunc auctor nec diam sit amet blandit.</p>
    <div class="row">
        {% for about_us in about_us %}
        <div class="col s12 m4 l4">
            <div class="card project-card">
                <div class="background pos-relative"
                    style="background-color: {{about_us.background_color}}; background-image:
                    url({{about_us.background_image}}); background-repeat: no-repeat; background-size: 100% 100%; height: 8em;">
                    <div class="pos-relative" style="height: 100%; width: 100%;">
                        {% if about_us.logo != "none" %}
                        <img class="pos-absolute-center" style="width: 200px;" src="{{about_us.logo}}" alt="logo" />
                        {% else %}
                        <p>meron</p>
                        {% endif %}
                    </div>
                </div>
                <div class="card-content">
                    <h5>{{about_us.header}}</h5>
                    <p class="font-weight-bold">{{about_us.sub_header}}</p>
                    <p>{{about_us.content}}</p>
                </div>
                <div class="card-action text-center">
                    <a href="{{about_us.url}}" target="_blank" class="btn teal-text transparent border-teal">Show
                        More</a>
                </div>
            </div>
        </div>
        {% endfor%}
    </div>
    <h5>Lorem ipsum dolor sit amet:</h5>
    <p>Integer nulla eros, ullamcorper quis velit in, varius scelerisque neque. Proin ac metus dolor. Mauris sed mattis
        risus. Nam sem nisl, suscipit eget justo ut, egestas rhoncus dolor. Donec efficitur metus in elit placerat
        semper. Suspendisse fringilla a massa hendrerit vulputate. Nunc ac feugiat justo. Aenean euismod, ipsum id
        vulputate ultrices, mauris sem fermentum elit, in fermentum ligula quam quis lacus. Orci varius natoque
        penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam molestie eu purus ac lacinia. Donec
        non blandit metus. Vivamus ac nibh rhoncus, pharetra risus eu, convallis lorem. Etiam sodales quam placerat,
        vehicula arcu eget, congue nulla. Etiam iaculis magna ut velit varius, a viverra libero auctor.</p>
</div>

{% include 'main/footer.html' %}
{% endblock %}

{% block footer %}
<script>
    var today = new Date()
    var hourNow = today.getHours()

    if (hourNow > 18) {
        console.log('%c Good Evening!', 'color: #070707')
        document.getElementById('banner-greetings').setAttribute(
            'style',
            'height: calc(10em + 30vmin); background: #314755; background: -webkit-linear-gradient(to right, #314755, #26a0da); background: linear-gradient(to right, #314755, #26a0da); border-bottom-left-radius: 700em 100em; border-bottom-right-radius: 700em 100em;'
        )
    } else if (hourNow > 12) {
        console.log('%c Good Afternoon!', 'color: #ff9800')
        document.getElementById('banner-greetings').setAttribute(
            'style',
            'height: calc(10em + 30vmin); background: #26D0CE; background: -webkit-linear-gradient(to right, #26D0CE, #1A2980); background: linear-gradient(to right, #26D0CE, #1A2980); border-bottom-left-radius: 700em 100em; border-bottom-right-radius: 700em 100em;'
        )
    } else if (hourNow > 0) {
        console.log('%c Good Morning! ', 'color: #ffeb3b')
        document.getElementById('banner-greetings').setAttribute(
            'style',
            'height: calc(10em + 30vmin); background: #348f50; background: -webkit-linear-gradient(to right, #009688, #56b4d3); background: linear-gradient(to right, #009688, #56b4d3); border-bottom-left-radius: 700em 100em; border-bottom-right-radius: 700em 100em;'
        )
    } else {
        console.log('%c Welcome to My Projects! ', 'color: #009688')
    }
</script>
{% endblock %}

technicalexercise/main/templates/main/contacts.html
{% extends 'main/header.html' %}

{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/main/contacts.css')}}">

{% include 'main/nav_bar.html' %}

<!-- Banner Map -->
<div id='map'></div>
<h4 class="text-center mt-1 mb-2">Thanks for taking the time to reach out. How can I help you today?</h4>
<div class="m-2">
    <div class="row">
        <div class="col s12 m12 l6">
            <div class="card">
                <div class="p-1 teal text-center">
                    <p class="r-fs-16 font-weight-bold white-text">Get In Touch</p>
                </div>
                <div class="card-content">
                    <div class="m-1 block">
                        <div class="inline-block">
                            <a class="btn-floating btn-large waves-effect waves-light teal">
                                <i class="fas fa-envelope"></i>
                            </a>
                        </div>
                        <div class="inline-block ml-2">
                            <p>root.jarias@gmail.com</p>
                        </div>
                    </div>
                    <div class="m-1 block">
                        <div class="inline-block">
                            <a class="btn-floating btn-large waves-effect waves-light teal">
                                <i class="fas fa-phone-square-alt"></i>
                            </a>
                        </div>
                        <div class="inline-block ml-2">
                            <p>0921-698-0972</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s12 m12 l6">
            <div class="card">
                <div class="p-1 teal text-center">
                    <p class="r-fs-16 font-weight-bold white-text">Have a question? Please enquire below</p>
                </div>
                <div class="card-content">
                    <div class="row">
                        <form class="col s12">
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="fas fa-user-circle prefix"></i>
                                    <input id="name" type="text" class="validate">
                                    <label for="name">Name</label>
                                </div>
                                <div class="input-field col s12">
                                    <i class="fas fa-envelope prefix"></i>
                                    <input id="email" type="tel" class="validate">
                                    <label for="email">Email</label>
                                </div>
                                <div class="input-field col s12">
                                    <i class="fas fa-comment-alt prefix"></i>
                                    <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
                                    <label for="icon_prefix2">Message</label>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="pos-right">
                        <a class="btn-large m-2" href="#">Submit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'main/footer.html' %}
{% endblock %}

{% block footer %}
<script src="{{ url_for('static', filename='js/main/contacts.js')}}"></script>
{% endblock %}

technicalexercise/main/templates/main/footer.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/main/footer.css')}}">

<footer class="page-footer">
    <div class="container text-center">
        <div class="row">
            <div class="col s12 m12 l12">
                <img class="footer-main-logo" src="{{ url_for('static', filename='img/main-logo-animated.svg')}}"
                    alt="dev-back-end">
                <h5>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet."
                </h5>
                <p>Created by John Rafael M. Arias</p>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2019 John Rafael Mantilla Arias
            <a class="grey-text text-lighten-4 right" href="#!">Created in Python Flask and MaterializeCSS</a>
        </div>
    </div>
</footer>

technicalexercise/main/templates/main/header.html
<title>{{ title }}</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Portfolio of John Rafael M. Arias" />
<meta name="keywords" content="Portfolio" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/global.css')}}">
<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

<!-- Map Box CDN -->
<link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet' />
<script src='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.js'></script>
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v2.0.0/turf.min.js' charset='utf-8'></script>
<!-- <link rel='stylesheet' href="{{ url_for('static', filename='css/font-awesome/css/fontawesome.min.css')}}"> -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<script src="https://kit.fontawesome.com/68ea31f05e.js" crossorigin="anonymous"></script>
{% extends "material/base.html" %}

technicalexercise/main/templates/main/nav_bar.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/main/nav_bar.css')}}">

<nav>
    <div class="nav-wrapper white">
        <a href="{{ url_for('main.base') }}" class="brand-logo teal-text">Lorem Ipsum</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{{ url_for('main.base') }}"><i class="fas fa-home teal-text"></i></a></li>
            <li><a href="{{ url_for('main.about_us') }}"><i class="fas fa-user-circle teal-text"></i></a></li>
            <li><a href="{{ url_for('main.contacts') }}"><i class="fas fa-address-card teal-text"></i></a></li>
        </ul>
    </div>
</nav>